#!/bin/bash

[[ "$USER" != "root" ]] && {

	echo "Root check failed! Please run script as root"
	exit 1

}


mkdir -p /usr/share/lex4/icon
cp lex4.png /usr/share/lex4/icon

cp lex4.desktop /usr/share/applications
